### ISSUE TITLE
Laravel version 5.4 issue

### ISSUE THREAD

**Issue by kwaik** [LaravelCollective/laravelcollective.com#11]
laravel framework version 5.4 cause function form::open missing token value, it return empty value.

After I edit app/http/kernel.php line 20, remark \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class. then everything become working.

**Comment by mlantz** [comment]
Thanks, I just stumbled onto this and the latest fix should have it resolved
