### ISSUE TITLE
5.4.5 Token empty while using Form::open

### ISSUE THREAD

**Issue by pelkamarcin** [LaravelCollective/laravelcollective.com#12]
Hi

today i updated library and all my forms stoped working. I detected that CSRF token embeded by default while using Form::open suddenly became empty. Downgrading to 5.4.4 fixed the problem.

I found that FormBuilder.php has empty csrfToken parm in constructor and in function called: getValueAttribute the token is empty.

**Comment by mlantz** [comment]
5.4.6 should have the problem solved - it was reported earlier today thanks.
