### ISSUE TITLE
LaravelCollective certificates

### ISSUE THREAD

**Issue by Willekur** [LaravelCollective/laravelcollective.com#16]
Hi guys and gals,

I wanted to check some things out on the laravelcollective website, then I got a message that the certificates are expired and the connection is not safe. Is this because of me or because something is wrong on the server?

Other than that, keep up the good work!

Cheers,

**Comment by tshafer** [comment]
Its a server problem. I don't have access to fix it and need to find time to spin up a new one so I can manage it.
