### ISSUE TITLE
Thin font weight is hard to read in Safari/Chrome.

### ISSUE THREAD

**Issue by jesseleite** [LaravelCollective/laravelcollective.com#2]
This is very subjective, as it deals with font choice... but I find the thin font weight is hard to read in Safari/Chrome.  Since you are going for Laravel inspired, why not use same fonts and font styles used on official docs: http://laravel.com/docs/5.0 ?

PS. Thanks for your work on maintaining these packages post-L5 :)

**Comment by RobinMalfait** [comment]
Hey @JerseyMilker Thanks for your issue. I'll look at this asap, and I will keep you posted in this issue.

**Comment by jesseleite** [comment]
Sounds great, thank you :)

**Comment by RobinMalfait** [comment]
Hey @JerseyMilker I've updated the fonts and some other stuff, example here:
http://laravelcollective.com/about
What do you think? :)

(P.S.: You might want to clear your cache)

**Comment by jesseleite** [comment]
Hey perfect :)  The docs are much easier to read now.  I think it was mostly the super thin font-weight you originally had.  Anyway thanks!
