### ISSUE TITLE
Suggestion Laravel Collective

### ISSUE THREAD

**Issue by eullercristian** [LaravelCollective/laravelcollective.com#5]
Dears, i have a sugestion for yours. Laravel could have a element form multicheckbox/radio. See  a example of implementation of Zend Framework: http://migre.me/s5V0J What do you think about that?  
The element could be Form::multicheckbox('name', array('L' => 'Large', 'S' => 'Small'));

**Comment by Decadence** [comment]
You should move this issue to "html" repository. This repo is for LC web site.

**Comment by mlantz** [comment]
To the best of my understanding the multiple checkboxes are functioning in the html package. If you would still like this feature please post it in that repo.
